# Generated by Django 2.2 on 2021-06-22 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210617_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentManager',
        ),
    ]
