# Generated by Django 2.2 on 2021-06-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_commentmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet_content',
            new_name='comment_content',
        ),
    ]
